version: '3.3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./backend/
    ports:
      - "8001:${BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "8000:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
